@base_uri=http://localhost:3333

###

# create-poll
POST {{base_uri}}/polls HTTP/1.1
content-type: application/json

{
    "title":"Testando",
    "options": ["Express", "Fastify", "NestJS", "HapiJS"]
}

###

# get-poll
GET {{base_uri}}/polls/84c681ee-0ee5-49f7-be81-7dca690e2cae HTTP/1.1

###

# vote-on-poll
POST {{base_uri}}/polls/84c681ee-0ee5-49f7-be81-7dca690e2cae/votes HTTP/1.1
content-type: application/json

{
    "pollOptionId": "3d8bdcad-7720-43a5-8a18-161e9ac41354"
}

# Web socket route: {{base_uri}}/polls/:pollId/results
# {{base_uri}}/polls/84c681ee-0ee5-49f7-be81-7dca690e2cae/results